// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Database.Migrations
{
    [DbContext(typeof(LabDbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Database.Models.CPU", b =>
                {
                    b.Property<int>("CPUId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Bitness")
                        .HasColumnType("text");

                    b.Property<string>("CacheMemory")
                        .HasColumnType("text");

                    b.Property<int?>("ComputerInfoComputerId")
                        .HasColumnType("integer");

                    b.Property<string>("Frequency")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NumberOfCores")
                        .HasColumnType("text");

                    b.HasKey("CPUId");

                    b.HasIndex("ComputerInfoComputerId");

                    b.ToTable("CPU");
                });

            modelBuilder.Entity("Database.Models.ComputerInfo", b =>
                {
                    b.Property<int>("ComputerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ComputerName")
                        .HasColumnType("text");

                    b.Property<string>("CreationTime")
                        .HasColumnType("text");

                    b.Property<string>("OSName")
                        .HasColumnType("text");

                    b.Property<string>("OSVersion")
                        .HasColumnType("text");

                    b.Property<string>("SystemFolder")
                        .HasColumnType("text");

                    b.Property<string>("UpdateTime")
                        .HasColumnType("text");

                    b.HasKey("ComputerId");

                    b.ToTable("ComputerInfo");
                });

            modelBuilder.Entity("Database.Models.ComputersToGPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ComputerId")
                        .HasColumnType("integer");

                    b.Property<int?>("GPUId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("GPUId");

                    b.ToTable("ComputersToGPU");
                });

            modelBuilder.Entity("Database.Models.ComputersToRAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ComputerId")
                        .HasColumnType("integer");

                    b.Property<int?>("RAMId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("RAMId");

                    b.ToTable("ComputersToRAM");
                });

            modelBuilder.Entity("Database.Models.ComputersToSSD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ComputerId")
                        .HasColumnType("integer");

                    b.Property<int?>("SSDId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("SSDId");

                    b.ToTable("ComputersToSSD");
                });

            modelBuilder.Entity("Database.Models.GPU", b =>
                {
                    b.Property<int>("GPUId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Frequency")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("VolumeMemory")
                        .HasColumnType("text");

                    b.HasKey("GPUId");

                    b.ToTable("Gpu");
                });

            modelBuilder.Entity("Database.Models.RAM", b =>
                {
                    b.Property<int>("RAMId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Frequency")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Volume")
                        .HasColumnType("text");

                    b.HasKey("RAMId");

                    b.ToTable("Ram");
                });

            modelBuilder.Entity("Database.Models.SSD", b =>
                {
                    b.Property<int>("SSDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Amount")
                        .HasColumnType("text");

                    b.Property<string>("MaxSpeedRead")
                        .HasColumnType("text");

                    b.Property<string>("MaxSpeedWrite")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("SSDId");

                    b.ToTable("Ssd");
                });

            modelBuilder.Entity("Database.Models.CPU", b =>
                {
                    b.HasOne("Database.Models.ComputerInfo", "ComputerInfo")
                        .WithMany()
                        .HasForeignKey("ComputerInfoComputerId");

                    b.Navigation("ComputerInfo");
                });

            modelBuilder.Entity("Database.Models.ComputersToGPU", b =>
                {
                    b.HasOne("Database.Models.ComputerInfo", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerId");

                    b.HasOne("Database.Models.GPU", "Gpu")
                        .WithMany()
                        .HasForeignKey("GPUId");

                    b.Navigation("Computer");

                    b.Navigation("Gpu");
                });

            modelBuilder.Entity("Database.Models.ComputersToRAM", b =>
                {
                    b.HasOne("Database.Models.ComputerInfo", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerId");

                    b.HasOne("Database.Models.RAM", "Ram")
                        .WithMany()
                        .HasForeignKey("RAMId");

                    b.Navigation("Computer");

                    b.Navigation("Ram");
                });

            modelBuilder.Entity("Database.Models.ComputersToSSD", b =>
                {
                    b.HasOne("Database.Models.ComputerInfo", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerId");

                    b.HasOne("Database.Models.SSD", "Ssd")
                        .WithMany()
                        .HasForeignKey("SSDId");

                    b.Navigation("Computer");

                    b.Navigation("Ssd");
                });
#pragma warning restore 612, 618
        }
    }
}
